name: Validate PR

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  lint-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Lint
        run: yarn lint:eslint

  lint-filename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: File name checker
        run: yarn lint:filename

  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Lint
        run: yarn lint:prettier

  lint-unused-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Lint unused TypeScript exports
        run: yarn lint:unused-exports

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Typecheck
        run: yarn typecheck

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Test
        run: yarn test:unit
